[versions]
activityCompose = "1.10.1"
agp = "8.10.1"
arrowCoreJvm = "2.1.2"
coilSvg = "3.3.0"
converterGson = "3.0.0"
datastoreCore = "1.1.4"
datastorePreferences = "1.1.4"
gson = "2.13.1"
hiltAndroid = "2.57.2"
hiltNavigationCompose = "1.2.0"
jakartaInjectApi = "2.0.1"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
kotlinxDatetime = "0.7.1-0.6.x-compat"
kotlinxSerializationJsonJvm = "1.9.0"
material = "1.12.0"
material3 = "1.3.2"
navigationCompose = "2.9.3"
okhttp = "5.1.0"
palette = "1.0.0"
paletteKtx = "1.0.0"
roomKtx = "2.7.2"
sqlcipher = "4.5.7"
tracing = "1.3.0"
tvMaterial = "1.0.1"
uiTooling = "1.8.3"
devtoolsKsp = "2.2.0-2.0.2"
mockk = "1.13.16"
coroutinesTest = "1.10.2"
turbine = "1.2.0"
archCoreTesting = "2.2.0"
hiltAndroidTesting = "2.57.2"
mockwebserver = "5.1.0"
composeUiTest = "1.8.3"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastoreCore" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "palette" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomKtx" }
androidx-sqlite-sqlcipher = { module = "androidx.sqlite:sqlite-sqlcipher", version.ref = "sqlcipher" }
androidx-tracing = { module = "androidx.tracing:tracing", version.ref = "tracing" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiTooling" }
androidx-tv-material = { module = "androidx.tv:tv-material", version.ref = "tvMaterial" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
arrow-core-jvm = { module = "io.arrow-kt:arrow-core-jvm", version.ref = "arrowCoreJvm" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coilSvg" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilSvg" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilSvg" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coilSvg" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakartaInjectApi" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json-jvm = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "kotlinxSerializationJsonJvm" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-coroutines = { module = "com.squareup.okhttp3:okhttp-coroutines", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterGson" }
retrofit-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "converterGson" }
# Testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "archCoreTesting" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUiTest" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUiTest" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsKsp" }
